language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: iUsLHwsYa7ZLaaEHnDPx8Vzdq9Cs+cdavjab3uSGN9eYKOCkVmi33EuomxXKG3WOQr5SKKwCSV7OCW3ON+8Bf+KPZjd8A9wOpdKH44eDee5W9BNZvbdMaptlWGYdCJ2TD2fhaRqRtyWVmkkH3QQkvKPgpb05Hn85TRxgWAXoH6E=
  - secure: VKJR8atE2CIQtpZNsE7eR/QCSk2HlqkZLS81OP2W9WXIJLS8dpj1CD9bciPuxzUZ8MrRuTG45IoXI1YKKmhx5C9j9wnsorZxiIKs0elnkBQWodCBeonL7vTXoD1cbpP5Cep/D5W7//HK9dZDxAGXtQah9xniIHcDgIVaXO+eai8=
